name: Maven CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        java-version: [11.0.17]

    steps:
    - name: Check out the repository
      uses: actions/checkout@v3

    - name: Set up JDK 11.0.17
      uses: actions/setup-java@v3
      with:
        java-version: ${{ matrix.java-version }}
        distribution: temurin

    - name: Set up Maven
      uses: actions/setup-java@v3
      with:
        java-package: jdk
        distribution: temurin
        cache: maven
        java-version: 11

    - name: Build with Maven
      run: mvn -B clean install

    - name: Run Tests
      run: mvn test
